package:
  name: diced
  version: "0.3"

source:
  git_url: ../
  git_tag: HEAD

build:
  number: 1
  
requirements:
  build:
    - python
    - setuptools
    - libdvid-cpp 0.2.post59
    - numpy
  run:
    - python
    - numpy
    - dvid
    - libdvid-cpp 0.2.post59
    - requests
    - enum34
    
#test:
#  imports:
#    - diced 

about:
  home: http://github.com/janelia-flyem/diced
  license: BSD (3-clause)
  license_file: LICENSE.txt
  summary: API to enable access to large-scale nD data volumes locally or on the cloud 
