package:
  name: diced
  version: "0.1"

source:
  git_url: ../
  git_tag: HEAD

build:
  number: 4
  
requirements:
  build:
    - python 2.7*
    - setuptools
  run:
    - python 2.7*  
    - numpy
    - dvid
    - libdvid-cpp
    - requests
    - enum34
    
#test:
#  imports:
#    - diced 

about:
  home: http://github.com/janelia-flyem/diced
  license: BSD (3-clause)
  license_file: LICENSE.txt
  summary: API to enable access to large-scale nD data volumes locally or on the cloud 
